version: '3.7'

services:
  ssh:
    environment:
      - PASSWORD=${SSH__MAIN__PASSWORD:?SSH__MAIN__PASSWORD}
      - ROOT_PASSWORD=${SSH__MAIN__ROOT_PASSWORD:?SSH__MAIN__ROOT_PASSWORD}
    image: ssh:local
    networks:
      - ssh_public_network
    ports:
      - 2222:22
    volumes:
      - airflow_dags:/dags
      - out:/out

networks:
  ssh_public_network:
    external: true

volumes:
  airflow_dags:
    name: airflow_dags
    external: true
  out:
    name: out
    external: true

