version: '3.6'
services:
  webserver:
    build: ${REL_HOST_PATH:?REL_HOST_PATH}/src
    entrypoint: ./entrypoint.sh run
    environment:
      - AIRFLOW__CORE__DAGS_FOLDER=${AIRFLOW__CORE__DAGS_FOLDER:?AIRFLOW__CORE__DAGS_FOLDER}
      - AIRFLOW__CORE__EXECUTOR=${AIRFLOW__CORE__EXECUTOR:?AIRFLOW__CORE__EXECUTOR}
      - AIRFLOW__CORE__FERNET_KEY=${AIRFLOW__CORE__FERNET_KEY:?AIRFLOW__CORE__FERNET_KEY}
      - AIRFLOW__CORE__LOAD_EXAMPLES=${AIRFLOW__CORE__LOAD_EXAMPLES:?AIRFLOW__CORE__LOAD_EXAMPLES}
      - AIRFLOW_PASSWORD=${AIRFLOW_PASSWORD:?AIRFLOW_PASSWORD}
      - AIRFLOW_USER=${AIRFLOW_USER:?AIRFLOW_USER}
      - AIRFLOW__WEBSERVER__AUTH_BACKEND=${AIRFLOW__WEBSERVER__AUTH_BACKEND:?AIRFLOW__WEBSERVER__AUTH_BACKEND}
      - AIRFLOW__WEBSERVER__AUTHENTICATE=${AIRFLOW__WEBSERVER__AUTHENTICATE:?AIRFLOW__WEBSERVER__AUTHENTICATE}
      - AIRFLOW__WEBSERVER__BASE_URL=${AIRFLOW__WEBSERVER__BASE_URL:?AIRFLOW__WEBSERVER__BASE_URL}
      - AIRFLOW__WEBSERVER__WEB_SERVER_PORT=${AIRFLOW__WEBSERVER__WEB_SERVER_PORT:?AIRFLOW__WEBSERVER__WEB_SERVER_PORT}
    healthcheck:
      test: curl -sfk ${AIRFLOW__WEBSERVER__BASE_URL:?AIRFLOW__WEBSERVER__BASE_URL}/health | grep healthy
      interval: 60s
      timeout: 60s
      retries: 3
    image: airflow:1.10.3
    networks:
      - default
    ports:
      - ${AIRFLOW_HOST_PORT:?AIRFLOW_HOST_PORT}:${AIRFLOW__WEBSERVER__WEB_SERVER_PORT:?AIRFLOW__WEBSERVER__WEB_SERVER_PORT}
    restart: unless-stopped
    volumes:
      - ${REL_HOST_PATH:?REL_HOST_PATH}/dags:${AIRFLOW__CORE__DAGS_FOLDER:?AIRFLOW__CORE__DAGS_FOLDER}

