version: '3.6'
services:
  worker:
    build: ${REL_HOST_PATH:?REL_HOST_PATH}/src
    entrypoint: ./entrypoint.sh airflow worker
    environment:
      - AIRFLOW__CORE__DAGS_FOLDER=${AIRFLOW__CORE__DAGS_FOLDER:?AIRFLOW__CORE__DAGS_FOLDER}
      - AIRFLOW__CORE__EXECUTOR=${AIRFLOW__CORE__EXECUTOR:?AIRFLOW__CORE__EXECUTOR}
      - AIRFLOW__CORE__FERNET_KEY=${AIRFLOW__CORE__FERNET_KEY:?AIRFLOW__CORE__FERNET_KEY}
      - AIRFLOW__CORE__LOAD_EXAMPLES=${AIRFLOW__CORE__LOAD_EXAMPLES:?AIRFLOW__CORE__LOAD_EXAMPLES}
      - AIRFLOW_PASSWORD=${AIRFLOW_PASSWORD:?AIRFLOW_PASSWORD}
      - AIRFLOW_USER=${AIRFLOW_USER:?AIRFLOW_USER}
      - AIRFLOW__WEBSERVER__AUTH_BACKEND=${AIRFLOW__WEBSERVER__AUTH_BACKEND:?AIRFLOW__WEBSERVER__AUTH_BACKEND}
      - AIRFLOW__WEBSERVER__AUTHENTICATE=${AIRFLOW__WEBSERVER__AUTHENTICATE:?AIRFLOW__WEBSERVER__AUTHENTICATE}
      - AIRFLOW__WEBSERVER__BASE_URL=${AIRFLOW__WEBSERVER__BASE_URL:?AIRFLOW__WEBSERVER__BASE_URL}
      - AIRFLOW__WEBSERVER__WEB_SERVER_PORT=${AIRFLOW__WEBSERVER__WEB_SERVER_PORT:?AIRFLOW__WEBSERVER__WEB_SERVER_PORT}
      - POSTGRES_DB=${POSTGRES_DB:?POSTGRES_DB}
      - POSTGRES_HOST=${POSTGRES_HOST:?POSTGRES_HOST}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:?POSTGRES_PASSWORD}
      - POSTGRES_PORT=${POSTGRES_PORT:?POSTGRES_PORT}
      - POSTGRES_USER=${POSTGRES_USER:?POSTGRES_USER}
      - REDIS_HOST=${REDIS_HOST:?REDIS_HOST}
      - REDIS_PASSWORD=${REDIS_PASSWORD:?REDIS_PASSWORD}
      - REDIS_PORT=${REDIS_PORT:?REDIS_PORT}
    image: airflow:1.10.3
    networks:
      - default
    restart: unless-stopped
    volumes:
      - ${REL_HOST_PATH:?REL_HOST_PATH}/dags:${AIRFLOW__CORE__DAGS_FOLDER:?AIRFLOW__CORE__DAGS_FOLDER}

