set -o errexit

psql -v ON_ERROR_STOP=1 --username "${POSTGRES_USER:?POSTGRES_USER}" <<-EOQUERY
     CREATE USER ${AIRFLOW_USER:?AIRFLOW_USER} WITH PASSWORD '${AIRFLOW_PASSWORD:?AIRFLOW_PASSWORD}';
     CREATE DATABASE ${AIRFLOW_DB:?AIRFLOW_DB};
     GRANT ALL PRIVILEGES ON DATABASE ${AIRFLOW_DB:?AIRFLOW_DB} TO ${AIRFLOW_USER:?AIRFLOW_USER};
EOQUERY
