version: '3.7'

services:
  postgres:
    command: postgres -c ssl=on -c ssl_cert_file=/ssl/postgres.cert -c ssl_key_file=/ssl/postgres.key
    environment:
      - PGDATA=/var/lib/postgresql/data
      - POSTGRES_DB=${POSTGRES__AIRFLOW__DB:?POSTGRES__AIRFLOW__DB}
      - POSTGRES_HOST=${POSTGRES__AIRFLOW__HOST:?POSTGRES__AIRFLOW__HOST}
      - POSTGRES_PASSWORD=${POSTGRES__AIRFLOW__PASSWORD:?POSTGRES__AIRFLOW__PASSWORD}
      - POSTGRES_PORT=${POSTGRES__AIRFLOW__PORT:?POSTGRES__AIRFLOW__PORT}
      - POSTGRES_USER=${POSTGRES__AIRFLOW__USER:?POSTGRES__AIRFLOW__USER}
    image: postgres:local
    networks:
      - airflow_public_network
    ports:
      - 54322:5432
    volumes:
      - airflow_pgdata:/var/lib/postgresql/data

  webserver:
    depends_on:
      - postgres
    deploy:
      labels:
        - traefik.docker.network=public_network
        - traefik.enable=true
        - traefik.frontend.rule=Host:${AIRFLOW__TRAEFIK__URL:?AIRFLOW__TRAEFIK__URL}
        - traefik.port=8080
        - traefik.tags=public
        # Traefik service that listens to HTTP
        - traefik.redirectorservice.frontend.entryPoints=http
        - traefik.redirectorservice.frontend.redirect.entryPoint=https
        # Traefik service that listens to HTTPS
        - traefik.frontend.auth.basic.users=${AIRFLOW__TRAEFIK__AUTH:?AIRFLOW__TRAEFIK__AUTH}
        - traefik.webservice.frontend.entryPoints=https
      placement:
        constraints:
          - node.role == manager
        preferences:
          - spread: node.id
      replicas: 1
    entrypoint: ./entrypoint.sh run
    environment:
      - AIRFLOW__CORE__DAGS_FOLDER=/dags
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__FERNET_KEY=${AIRFLOW__MAIN__FERNET_KEY:?AIRFLOW__MAIN__FERNET_KEY}
      - AIRFLOW__CORE__LOAD_EXAMPLES=false
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=${AIRFLOW__URI__POSTGRESQL_PSYCOPG2:?AIRFLOW__URI__POSTGRESQL_PSYCOPG2}
      - AIRFLOW__WEBSERVER__BASE_URL=http://0.0.0.0:8080
      - AIRFLOW__WEBSERVER__WEB_SERVER_PORT=8080
      # login configuration
      - AIRFLOW_USER_ADMIN=${AIRFLOW__MAIN__JSON_USER:?AIRFLOW__MAIN__JSON_USER}
      - AIRFLOW__WEBSERVER__AUTH_BACKEND=airflow.contrib.auth.backends.password_auth
      - AIRFLOW__WEBSERVER__AUTHENTICATE=true
      - AIRFLOW__WEBSERVER__RBAC=true
    healthcheck:
      interval: 30s
      retries: 3
      test: curl -sfk http://0.0.0.0:8080/health | grep healthy
      timeout: 30s
    image: airflow:local
    networks:
      - airflow_public_network
      - public_network
    volumes:
      - airflow_dags:/dags
      - airflow_conf:/airflow

networks:
  airflow_public_network:
    external: true
  public_network:
    external: true

volumes:
  airflow_pgdata:
    name: airflow_pgdata
    external: false
  airflow_conf:
    name: airflow_conf
    external: false
  airflow_dags:
    name: airflow_dags
    external: true
