version: '3.6'
services:
  pgadmin:
    environment:
       - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL:?PGADMIN_DEFAULT_EMAIL}
       - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD:?PGADMIN_DEFAULT_PASSWORD}
    image: ${PGADMIN_IMAGE:?PGADMIN_IMAGE}
    labels:
      - traefik.enable=${TRAEFIK_ENABLE:?TRAEFIK_ENABLE}
      - traefik.frontend.auth.basic=${TRAEFIK_AUTH_BASIC:?TRAEFIK_AUTH_BASIC}
      - traefik.frontend.rule=Host:${TRAEFIK_INTERFACE_DOMAIN:?TRAEFIK_INTERFACE_DOMAIN}
      - traefik.port=${PGADMIN_PORT:?PGADMIN_PORT}
    ports:
       - ${PGADMIN_HOST_PORT:?PGADMIN_HOST_PORT}:${PGADMIN_PORT:?PGADMIN_PORT}
    restart: unless-stopped
    volumes:
       - pgadmin-data:/var/lib/pgadmin
       - pgadmin-config:/pgadmin4

volumes:
  pgadmin-data:
  pgadmin-config:
