version: '3'

services:
  traefik:
    image: traefik:v2.6.1
    container_name: "${DOCKER_NAME}_traefik"
    command:
      # provider
      - --providers.docker=true
      # Enable the API handler in insecure mode,
      # which means that the Traefik API will be available directly
      # on the entry point named traefik.
      - --api.insecure=false
      # Defines the path to the configuration file with the certificates list.
      - --providers.file.filename=/root/.config/ssl.toml
      # Define Traefik entry points to port [80] for http and port [443] for https.
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
    networks:
      # Define the network on which traefik is going to operate.
      - traefik-public-network
    ports:
      # Open traefik http [80] and https [443] ports.
      - '80:80'
      - '443:443'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      # Mount the configuration file with the certificates list.
      - ./traefik-ssl.toml:/root/.config/ssl.toml
      # Mount the folder containing the certificates for https.
      - ./certs/:/certs/
    labels:
      - "traefik.enable=true"
      # Enable Traefik API handler entrypoint on http.
      - "traefik.http.routers.traefik-http.entrypoints=web"
      # authentication
      - traefik.http.middlewares.traefik-auth.basicauth.users=${TRAEFIK_DASHBOARD_AUTH}
      # Define Traefik API handler http host.
      # set network
      - "traefik.docker.network=traefik-public"
      #- traefik.http.routers.traefik-http.rule=Host(`s0.lan`)
      - traefik.http.routers.traefik-http.rule=HostRegexp(`{www:(?:www\.)?}traefik.{domain:[a-z0-9.-_]+}`)
      # Define http middleware and redirection to https.
      - "traefik.http.routers.traefik-http.middlewares=traefik-https"
      - "traefik.http.middlewares.traefik-https.redirectscheme.scheme=https"
      # Enable Traefik API handler entrypoint on https.
      - "traefik.http.routers.traefik.entrypoints=websecure"
      # By default the Traefik API handler operates on the port [8080].
      # Define a load balancer to route the entry point to [8080].
      - "traefik.http.services.traefik.loadbalancer.server.port=8080"
      # Define Traefik API handler host.
      #- traefik.http.routers.traefik.rule=Host(`s0.lan`)
      - traefik.http.routers.traefik.rule=HostRegexp(`{www:(?:www\.)?}traefik.{domain:[a-z0-9.-_]+}`)
      #- traefik.http.routers.traefik.rule=HostRegexp(`{www:(?:www\.)?}traefik.{domain:[a-z0-9.-_]+}`)
      # Instructs Traefik that the current router is dedicated to HTTPS requests only.
      - "traefik.http.routers.traefik.tls=true"
      # define services
      - traefik.http.routers.traefik-http.service=api@internal
      - traefik.http.routers.traefik.service=api@internal

  err_page:
    image: ghcr.io/tarampampam/error-pages
    container_name: "${DOCKER_NAME}_err_page"
    networks:
      - traefik-public-network
    labels:
      # Enable Whoami handler entrypoint on http.
      - "traefik.http.routers.${DOCKER_NAME}_err_page-http.entrypoints=web"
      # Define Whoami handler http host.
      - traefik.http.routers.${DOCKER_NAME}_err_page-http.rule=HostRegexp(`{www:(?:www\.)?}error.{domain:[a-z0-9.-_]+}`)
      # Define http middleware and redirection to https.
      - "traefik.http.routers.${DOCKER_NAME}_err_page-http.middlewares=${DOCKER_NAME}_err_page-https"
      - "traefik.http.middlewares.${DOCKER_NAME}_err_page-https.redirectscheme.scheme=https"
      # Enable Whoami handler entrypoint on https.
      - "traefik.http.routers.${DOCKER_NAME}_err_page.entrypoints=websecure"
      # Define Whoami handler host.
      - traefik.http.routers.${DOCKER_NAME}_err_page.rule=HostRegexp(`{www:(?:www\.)?}error.{domain:[a-z0-9.-_]+}`)
      # Instructs Whoami that the current router is dedicated to HTTPS requests only.
      - "traefik.http.routers.${DOCKER_NAME}_err_page.tls=true"
      # Define on which network Traefik is operating.
      - "traefik.docker.network=traefik-public-network"
      # Added
      #- traefik.http.routers.${DOCKER_NAME}_err_page.service=error-pages
      - "traefik.http.services.${DOCKER_NAME}_err_page.loadbalancer.server.port=8080"

networks:
  traefik-public-network:
    external: true
