version: '3.6'

services:
  traefik:
    image: ${TRAEFIK_IMAGE:?TRAEFIK_IMAGE}
    labels:
      - traefik.enable=${TRAEFIK_ENABLE:?TRAEFIK_ENABLE}
      - traefik.frontend.auth.basic=${TRAEFIK_AUTH_BASIC:?TRAEFIK_AUTH_BASIC}
      - traefik.frontend.rule=Host:${TRAEFIK_INTERFACE_DOMAIN:?TRAEFIK_INTERFACE_DOMAIN}
      - traefik.port=${TRAEFIK_PORT:?TRAEFIK_PORT}
    networks:
      - default
    ports:
      - ${TRAEFIK_HOST_PORT_HTTP:?TRAEFIK_HOST_PORT_HTTP}:${TRAEFIK_PORT_HTTP:?TRAEFIK_PORT_HTTP}
      - ${TRAEFIK_HOST_PORT_HTTPS:?TRAEFIK_HOST_PORT_HTTPS}:${TRAEFIK_PORT_HTTPS:?TRAEFIK_PORT_HTTPS}
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${TRAEFIK_CONFIG_HOST_PATH:?TRAEFIK_CONFIG_HOST_PATH}:${TRAEFIK_CONFIG_PATH:?TRAEFIK_CONFIG_PATH}:ro
      - ${TRAEFIK_ACME_HOST_PATH:?TRAEFIK_ACME_HOST_PATH}:${TRAEFIK_ACME_PATH:?TRAEFIK_ACME_PATH}
 
