version: '3.6'

services:
  jupyter:
    deploy:
      labels:
        - traefik.docker.network=public_network
        - traefik.enable=true
        - traefik.frontend.rule=Host:${LAB__TRAEFIK__URL:?LAB__TRAEFIK__URL}
        - traefik.port=8000
        - traefik.tags=public
        # Traefik service that listens to HTTP
        - traefik.redirectorservice.frontend.entryPoints=http
        - traefik.redirectorservice.frontend.redirect.entryPoint=https
        # Traefik service that listens to HTTPS
        - traefik.frontend.auth.basic.users=${LAB__TRAEFIK__AUTH:?LAB__TRAEFIK__AUTH}
        - traefik.webservice.frontend.entryPoints=https
    healthcheck:
      interval: 30s
      retries: 3
      test: curl -sfk http://0.0.0.0:8000/hub/api | grep version
      timeout: 30s
    environment:
      - USER_LOGIN=${USER_LOGIN:?USER_LOGIN}
      - ROOT_PASSWORD=${LAB__MAIN__ROOT_PASSWORD:?LAB__MAIN__ROOT_PASSWORD}
    image: lab:local
    networks:
      - airflow_public_network
      - lab_public_network
      - public_network
    ports:
      - 22
      - 8000
    volumes:
      - airflow_conf:/airflow
      - airflow_dags:/dags

networks:
  airflow_public_network:
    external: true
  lab_public_network:
    external: true
  public_network:
    external: true

volumes:
  airflow_conf:
    external: true
  airflow_dags:
    external: true
