POSTGRES_USER=${POSTGRES_USER:-postgres}
POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
POSTGRES_DB=${POSTGRES_DB:-postgres}
dba=${POSTGRES_DB}_dba
rwa=${POSTGRES_DB}_rwa
rw=${POSTGRES_DB}_rw
ro=${POSTGRES_DB}_ro
vo=${POSTGRES_DB}_vo


psql -v ON_ERROR_STOP=1 --dbname=${POSTGRES_DB} --username=${POSTGRES_USER} <<-EOQUERY

CREATE ROLE ${vo} NOCREATEDB NOCREATEROLE NOINHERIT NOLOGIN;
CREATE ROLE ${ro} NOCREATEDB NOCREATEROLE NOINHERIT NOLOGIN;
CREATE ROLE ${rw} NOCREATEDB NOCREATEROLE NOINHERIT NOLOGIN;
CREATE ROLE ${rwa} NOCREATEDB NOCREATEROLE NOINHERIT NOLOGIN;
CREATE ROLE ${dba} NOCREATEDB CREATEROLE NOINHERIT LOGIN PASSWORD '${POSTGRES_PASSWORD:0:32}';

GRANT ${dba} to ${rwa};

REVOKE ALL ON DATABASE postgres FROM PUBLIC, ${vo}, ${ro}, ${rw}, ${rwa}, ${dba};

GRANT ALL ON DATABASE ${POSTGRES_DB} TO ${dba};
ALTER DATABASE ${POSTGRES_DB} OWNER TO ${dba};
CREATE SCHEMA datamarts;

ALTER SCHEMA PUBLIC OWNER TO ${dba};
ALTER SCHEMA datamarts OWNER TO ${dba};

-- USERS
CREATE ROLE ${POSTGRES_USER}_${vo} LOGIN PASSWORD '${POSTGRES_PASSWORD:0:8}' IN ROLE ${vo};
CREATE ROLE ${POSTGRES_USER}_${ro} LOGIN PASSWORD '${POSTGRES_PASSWORD:0:16}' IN ROLE ${ro};
CREATE ROLE ${POSTGRES_USER}_${rw} LOGIN PASSWORD '${POSTGRES_PASSWORD:0:24}' IN ROLE ${rw};
CREATE ROLE ${POSTGRES_USER}_${rwa} LOGIN PASSWORD '${POSTGRES_PASSWORD:0:32}' IN ROLE ${rwa};

EOQUERY


psql -v ON_ERROR_STOP=1 --dbname=${POSTGRES_DB} --username=${dba} <<-EOQUERY

-- SET dba
GRANT ALL ON SCHEMA PUBLIC, datamarts TO ${dba};
GRANT ALL ON ALL TABLES IN SCHEMA PUBLIC, datamarts TO ${dba};
ALTER DEFAULT PRIVILEGES IN SCHEMA PUBLIC, datamarts GRANT ALL ON TABLES TO ${dba};
ALTER DEFAULT PRIVILEGES GRANT ALL ON SEQUENCES TO ${dba};
ALTER DEFAULT PRIVILEGES GRANT ALL ON FUNCTIONS TO ${dba};

-- REVOKE ACCESS OF OTHERS
REVOKE ALL ON ALL TABLES IN SCHEMA PUBLIC, datamarts FROM PUBLIC, ${vo}, ${ro}, ${rw}, ${rwa};
REVOKE ALL ON ALL SEQUENCES IN SCHEMA PUBLIC, datamarts FROM PUBLIC, ${vo}, ${ro}, ${rw}, ${rwa};
REVOKE ALL ON ALL FUNCTIONS IN SCHEMA PUBLIC, datamarts FROM PUBLIC, ${vo}, ${ro}, ${rw}, ${rwa};

ALTER DEFAULT PRIVILEGES REVOKE ALL ON TABLES FROM PUBLIC, ${vo}, ${ro}, ${rw}, ${rwa};
ALTER DEFAULT PRIVILEGES REVOKE ALL ON SEQUENCES FROM PUBLIC, ${vo}, ${ro}, ${rw}, ${rwa};
ALTER DEFAULT PRIVILEGES REVOKE ALL ON FUNCTIONS FROM PUBLIC, ${vo}, ${ro}, ${rw}, ${rwa};

REVOKE ALL ON SCHEMA PUBLIC, datamarts FROM PUBLIC, ${vo}, ${ro}, ${rw}, ${rwa};
REVOKE ALL ON DATABASE ${POSTGRES_DB} FROM PUBLIC, ${vo}, ${ro}, ${rw}, ${rwa};

-- GRANT SOME ACCESS TO DEFAULT ROLES
GRANT CONNECT ON DATABASE ${POSTGRES_DB} TO ${vo}, ${ro}, ${rw}, ${rwa};
GRANT USAGE ON SCHEMA PUBLIC, datamarts TO ${ro}, ${rw}, ${rwa};
GRANT USAGE ON SCHEMA datamarts TO ${vo};

GRANT SELECT ON ALL TABLES IN SCHEMA datamarts TO ${vo};
GRANT SELECT ON ALL TABLES IN SCHEMA PUBLIC, datamarts TO ${ro};
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA PUBLIC, datamarts TO ${rw}, ${rwa};

ALTER DEFAULT PRIVILEGES IN SCHEMA datamarts GRANT SELECT ON TABLES TO ${vo};
ALTER DEFAULT PRIVILEGES IN SCHEMA PUBLIC, datamarts GRANT SELECT ON TABLES TO ${ro};
ALTER DEFAULT PRIVILEGES IN SCHEMA PUBLIC, datamarts GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO ${rw}, ${rwa};

ALTER DEFAULT PRIVILEGES GRANT SELECT ON SEQUENCES TO ${ro};
ALTER DEFAULT PRIVILEGES GRANT ALL ON SEQUENCES TO ${rw}, ${rwa};

ALTER DEFAULT PRIVILEGES GRANT EXECUTE ON FUNCTIONS TO ${ro};
ALTER DEFAULT PRIVILEGES GRANT ALL ON FUNCTIONS TO ${rw}, ${rwa};

EOQUERY
