POSTGRES_PASSWORD=${POSTGRES_USER:-postgres}

# update user
psql -v ON_ERROR_STOP=0 --dbname=${POSTGRES_DB:-postgres} --username=${POSTGRES_USER:-postgres} <<-EOQUERY

CREATE ROLE viewonly;
CREATE ROLE readonly;
CREATE ROLE readwrite;

CREATE SCHEMA datamarts;

-- REVOKE ACCESS
REVOKE ALL ON ALL TABLES IN SCHEMA PUBLIC, datamarts FROM PUBLIC, viewonly, readonly, readwrite;
REVOKE ALL ON ALL SEQUENCES IN SCHEMA PUBLIC, datamarts FROM PUBLIC, viewonly, readonly, readwrite;
REVOKE ALL ON ALL FUNCTIONS IN SCHEMA PUBLIC, datamarts FROM PUBLIC, viewonly, readonly, readwrite;

ALTER DEFAULT PRIVILEGES REVOKE ALL ON TABLES FROM PUBLIC, viewonly, readonly, readwrite;
ALTER DEFAULT PRIVILEGES REVOKE ALL ON SEQUENCES FROM PUBLIC, viewonly, readonly, readwrite;
ALTER DEFAULT PRIVILEGES REVOKE ALL ON FUNCTIONS FROM PUBLIC, viewonly, readonly, readwrite;

REVOKE ALL ON SCHEMA PUBLIC, datamarts FROM PUBLIC, viewonly, readonly, readwrite;
REVOKE ALL ON DATABASE ${POSTGRES_DB:-postgres} FROM PUBLIC, viewonly, readonly, readwrite;
REVOKE ALL ON DATABASE postgres FROM PUBLIC, viewonly, readonly, readwrite;

-- GRANT
GRANT CONNECT ON DATABASE ${POSTGRES_DB:-postgres} TO viewonly, readonly, readwrite;
GRANT USAGE ON SCHEMA public, datamarts TO readonly, readwrite;
GRANT USAGE ON SCHEMA datamarts TO viewonly;

GRANT SELECT ON ALL TABLES IN SCHEMA datamarts TO viewonly ;
GRANT SELECT ON ALL TABLES IN SCHEMA public, datamarts TO readonly ;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public, datamarts TO readwrite ;

ALTER DEFAULT PRIVILEGES IN SCHEMA datamarts GRANT SELECT ON TABLES TO PUBLIC, viewonly;
ALTER DEFAULT PRIVILEGES IN SCHEMA public, datamarts GRANT SELECT ON TABLES TO readonly;
ALTER DEFAULT PRIVILEGES IN SCHEMA public, datamarts GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO readwrite;

ALTER DEFAULT PRIVILEGES GRANT SELECT ON SEQUENCES TO readonly;
ALTER DEFAULT PRIVILEGES GRANT ALL ON SEQUENCES TO readwrite;

ALTER DEFAULT PRIVILEGES GRANT EXECUTE ON FUNCTIONS TO readonly;
ALTER DEFAULT PRIVILEGES GRANT ALL ON FUNCTIONS TO readwrite;

-- USERS
CREATE USER ${POSTGRES_USER:-postgres}_viewonly WITH PASSWORD '${POSTGRES_PASSWORD:0:8}' WITH ROLE viewonly;
CREATE USER ${POSTGRES_USER:-postgres}_readonly WITH PASSWORD '${POSTGRES_PASSWORD:0:16}' WITH ROLE readonly;
CREATE USER ${POSTGRES_USER:-postgres}_readwrite WITH PASSWORD '${POSTGRES_PASSWORD:0:32}' WITH ROLE readwrite;

EOQUERY

