CREATE ROLE dbo;

CREATE OR REPLACE FUNCTION trg_unset_owner()
 RETURNS event_trigger
 LANGUAGE plpgsql
AS $$
BEGIN
  reset role;
  raise notice 'unset, user: %', current_user;
END;
$$;

ALTER FUNCTION public.trg_unset_owner() OWNER TO dbo;

CREATE EVENT TRIGGER trg_unset_owner
ON ddl_command_end
WHEN tag IN (S
	'CREATE ACCESS METHOD',
	'CREATE AGGREGATE',
	'CREATE CAST',
	'CREATE COLLATION',
	'CREATE CONVERSION',
	'CREATE DOMAIN',
	'CREATE EXTENSION',
	'CREATE FOREIGN DATA WRAPPER',
	'CREATE FOREIGN TABLE',
	'CREATE FUNCTION',
	'CREATE INDEX',
	'CREATE LANGUAGE',
	'CREATE MATERIALIZED VIEW',
	'CREATE OPERATOR',
	'CREATE OPERATOR CLASS',
	'CREATE OPERATOR FAMILY',
	'CREATE POLICY',
	'CREATE PROCEDURE',
	'CREATE PUBLICATION',
	'CREATE RULE',
	'CREATE SCHEMA',
	'CREATE SEQUENCE',
	'CREATE SERVER',
	'CREATE STATISTICS',
	'CREATE SUBSCRIPTION',
	'CREATE TABLE',
	'CREATE TABLE AS',
	'CREATE TEXT SEARCH CONFIGURATION',
	'CREATE TEXT SEARCH DICTIONARY',
	'CREATE TEXT SEARCH PARSER',
	'CREATE TEXT SEARCH TEMPLATE',
	'CREATE TRIGGER',
	'CREATE TYPE',
	'CREATE USER MAPPING',
	'CREATE VIEW'
)
EXECUTE PROCEDURE trg_unset_owner();

CREATE OR REPLACE FUNCTION trg_set_owner()
 RETURNS event_trigger
 LANGUAGE plpgsql
AS $$
BEGIN
  set role dbo;
  raise notice 'user: %', current_user;
END;
$$;

ALTER FUNCTION trg_set_owner()
    OWNER TO dbo;

CREATE EVENT TRIGGER trg_set_owner
ON ddl_command_start
WHEN tag IN (
	'CREATE ACCESS METHOD',
	'CREATE AGGREGATE',
	'CREATE CAST',
	'CREATE COLLATION',
	'CREATE CONVERSION',
	'CREATE DOMAIN',
	'CREATE EXTENSION',
	'CREATE FOREIGN DATA WRAPPER',
	'CREATE FOREIGN TABLE',
	'CREATE FUNCTION',
	'CREATE INDEX',
	'CREATE LANGUAGE',
	'CREATE MATERIALIZED VIEW',
	'CREATE OPERATOR',
	'CREATE OPERATOR CLASS',
	'CREATE OPERATOR FAMILY',
	'CREATE POLICY',
	'CREATE PROCEDURE',
	'CREATE PUBLICATION',
	'CREATE RULE',
	'CREATE SCHEMA',
	'CREATE SEQUENCE',
	'CREATE SERVER',
	'CREATE STATISTICS',
	'CREATE SUBSCRIPTION',
	'CREATE TABLE',
	'CREATE TABLE AS',
	'CREATE TEXT SEARCH CONFIGURATION',
	'CREATE TEXT SEARCH DICTIONARY',
	'CREATE TEXT SEARCH PARSER',
	'CREATE TEXT SEARCH TEMPLATE',
	'CREATE TRIGGER',
	'CREATE TYPE',
	'CREATE USER MAPPING',
	'CREATE VIEW'
)
EXECUTE PROCEDURE trg_set_owner();

