-- create base roles
DROP ROLE IF EXISTS ro;
CREATE ROLE ro NOCREATEDB NOCREATEROLE NOINHERIT NOLOGIN;
DROP ROLE IF EXISTS rw;
CREATE ROLE rw NOCREATEDB NOCREATEROLE NOINHERIT NOLOGIN;
DROP ROLE IF EXISTS dba;
CREATE ROLE dba NOCREATEDB NOCREATEROLE NOINHERIT NOLOGIN;
DROP ROLE IF EXISTS dbo;
CREATE ROLE dbo NOCREATEDB NOCREATEROLE NOINHERIT NOLOGIN;

GRANT dbo TO dba;

-- set create, connect, owner (db:postgres)
REVOKE CREATE, CONNECT, TEMP ON DATABASE postgres FROM PUBLIC, ro, rw, dba, dbo;
GRANT CONNECT ON DATABASE postgres TO PUBLIC, ro, rw, dba;
GRANT CREATE, CONNECT, TEMP ON DATABASE postgres TO dbo;
ALTER DATABASE postgres OWNER TO dbo;
ALTER SCHEMA PUBLIC OWNER TO dbo;

-- set default permissions on schemas
ALTER DEFAULT PRIVILEGES REVOKE USAGE, CREATE ON SCHEMAS FROM PUBLIC, ro, rw, dba, dbo;
ALTER DEFAULT PRIVILEGES GRANT USAGE ON SCHEMAS TO ro, rw, dba;
ALTER DEFAULT PRIVILEGES GRANT USAGE, CREATE ON SCHEMAS TO dbo;

-- set default permissions on tables
ALTER DEFAULT PRIVILEGES REVOKE ALL ON TABLES FROM PUBLIC, ro, rw, dba, dbo;
ALTER DEFAULT PRIVILEGES GRANT SELECT ON TABLES TO ro;
ALTER DEFAULT PRIVILEGES GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO rw;
ALTER DEFAULT PRIVILEGES GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER ON TABLES TO dba, dbo;

-- set default privileges for sequences
ALTER DEFAULT PRIVILEGES REVOKE ALL ON SEQUENCES FROM PUBLIC, ro;
ALTER DEFAULT PRIVILEGES GRANT SELECT ON SEQUENCES TO ro;
ALTER DEFAULT PRIVILEGES GRANT USAGE, SELECT ON SEQUENCES TO ro;
ALTER DEFAULT PRIVILEGES GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO rw, dba, dbo;

-- set default privileges for functions
ALTER DEFAULT PRIVILEGES REVOKE ALL ON FUNCTIONS FROM PUBLIC, ro;
ALTER DEFAULT PRIVILEGES GRANT EXECUTE ON FUNCTIONS TO rw, dba, dbo;



--- set privileges on schema (schema:public)
REVOKE ALL ON SCHEMA PUBLIC FROM PUBLIC, ro, rw, dba, dbo;
GRANT USAGE ON SCHEMA PUBLIC TO ro, rw, dba;
GRANT CREATE, USAGE ON SCHEMA PUBLIC TO dbo;

--- set privileges on tables (schema:public)
REVOKE ALL ON ALL TABLES IN SCHEMA PUBLIC FROM ro, rw, dba, dbo;
GRANT SELECT ON ALL TABLES IN SCHEMA PUBLIC TO ro;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA PUBLIC TO rw;
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE, REFERENCES, TRIGGER ON ALL TABLES IN SCHEMA PUBLIC TO dba, dbo;

--- set privileges on sequences (schema:public)
REVOKE ALL ON ALL SEQUENCES IN SCHEMA PUBLIC FROM PUBLIC, ro, rw, dba, dbo;
GRANT SELECT ON ALL SEQUENCES IN SCHEMA PUBLIC TO ro;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA PUBLIC TO rw;
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA PUBLIC TO dba, dbo;

--- set privileges on functions (schema:public)
REVOKE ALL ON ALL FUNCTIONS IN SCHEMA PUBLIC FROM PUBLIC, ro, rw, dba, dbo;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA PUBLIC TO rw, dba, dbo;


