psql -v ON_ERROR_STOP=1 --dbname=airflow --username="${POSTGRES_USER:?POSTGRES_USER}" <<-EOQUERY
     CREATE USER ${POSTGRES__AIRFLOW_READ__USER:?POSTGRES__AIRFLOW_READ__USER} WITH ENCRYPTED PASSWORD '${POSTGRES__AIRFLOW_READ__PASSWORD:?POSTGRES__AIRFLOW_READ__PASSWORD}';
     GRANT airflow_readonly TO ${POSTGRES__AIRFLOW_READ__USER:?POSTGRES__AIRFLOW_READ__USER};
EOQUERY
