psql -v ON_ERROR_STOP=1 --dbname=airflow --username="${POSTGRES_USER:?POSTGRES_USER}" <<-EOQUERY
     CREATE USER ${POSTGRES__AIRFLOW__USER:?POSTGRES__AIRFLOW__USER} WITH ENCRYPTED PASSWORD '${POSTGRES__AIRFLOW__PASSWORD:?POSTGRES__AIRFLOW__PASSWORD}';
     GRANT airflow_readwrite TO ${POSTGRES__AIRFLOW__USER:?POSTGRES__AIRFLOW__USER};
EOQUERY
