version: '3.7'
services:
  postgres:
    command: postgres -c ssl=on -c ssl_cert_file=/ssl/postgres.cert -c ssl_key_file=/ssl/postgres.key 
    environment:
      - POSTGRES_DB=${POSTGRES__MAIN__DB:?POSTGRES__MAIN__DB}
      - POSTGRES_HOST=${POSTGRES__MAIN__HOST:?POSTGRES__MAIN__HOST}
      - POSTGRES_PASSWORD=${POSTGRES__MAIN__PASSWORD:?POSTGRES__MAIN__PASSWORD}
      - POSTGRES_PORT=${POSTGRES__MAIN__PORT:?POSTGRES__MAIN__PORT}
      - POSTGRES_USER=${POSTGRES__MAIN__USER:?POSTGRES__MAIN__USER}
    image: postgres:local
    networks:
      - postgres_public_network
    ports:
      - 54321:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

networks:
  postgres_public_network:
    external: true

volumes:
  pgdata:
