version: '3.6'
services:
  postgres:
    build: .
    image: postgres:latest
    #command: postgres -c ssl=on -c ssl_cert_file=/etc/ssl/domain.crt -c ssl_key_file=/etc/ssl/domain.key
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${POSTGRES_USER:?POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:?POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB:?POSTGRES_DB}
    ports:
      - 5489:5432
