version: '3.6'
services:
  postgres:
    build: ./src
    #command: postgres -c ssl=on -c ssl_cert_file=/etc/ssl/domain.crt -c ssl_key_file=/etc/ssl/domain.key
    environment:
      - POSTGRES_USER=${POSTGRES_USER:?POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:?POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB:?POSTGRES_DB}
      - AIRFLOW_USER=${AIRFLOW_USER:?AIRFLOW_USER}
      - AIRFLOW_PASSWORD=${AIRFLOW_PASSWORD:?AIRFLOW_PASSWORD}
      - AIRFLOW_DB=${AIRFLOW_DB:?AIRFLOW_DB}
    image: postgres:local
    labels:
      - traefik.enable=${TRAEFIK_ENABLE:?TRAEFIK_ENABLE}
      - traefik.frontend.auth.basic=${TRAEFIK_AUTH_BASIC:?TRAEFIK_AUTH_BASIC}
      - traefik.frontend.rule=Host:${TRAEFIK_INTERFACE_DOMAIN:?TRAEFIK_INTERFACE_DOMAIN}
      - traefik.port=${POSTGRES_PORT:?POSTGRES_PORT}
    ports:
      - 15432:${POSTGRES_PORT:?POSTGRES_PORT}
    restart: unless-stopped
