version: '3.6'
services:
  postgres:
    build: ./src
    #command: postgres -c ssl=on -c ssl_cert_file=/etc/ssl/domain.crt -c ssl_key_file=/etc/ssl/domain.key
    environment:
      - POSTGRES_USER=${POSTGRES__MAIN__USERNAME:?POSTGRES__MAIN__USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES__MAIN__PASSWORD:?POSTGRES__MAIN__PASSWORD}
      - POSTGRES_DB=${POSTGRES__MAIN__DB:?POSTGRES__MAIN__DB}
      - AIRFLOW_USER=${POSTGRES__AIRFLOW__USERNAME:?POSTGRES__AIRFLOW__USERNAME}
      - AIRFLOW_PASSWORD=${POSTGRES__AIRFLOW__PASSWORD:?POSTGRES__AIRFLOW__PASSWORD}
      - AIRFLOW_DB=${POSTGRES__AIRFLOW__DB:?POSTGRES__AIRFLOW__DB}
    image: postgres:local
    labels:
      - traefik.enable=true
      - traefik.frontend.auth.basic=${POSTGRES__TRAEFIK__AUTH:?POSTGRES__TRAEFIK__AUTH}
      - traefik.frontend.rule=Host:${POSTGRES__TRAEFIK__URL:?POSTGRES__TRAEFIK__URL}
      - traefik.port=5432
    ports:
      - 5432
    restart: unless-stopped
    volumes:
      - ./create-user:/docker-entrypoint-initdb.d/100-create-user
      - ./create-db:/docker-entrypoint-initdb.d/200-create-db
      - ./pgdump:/docker-entrypoint-initdb.d/300-pgdump
