version: '3.6'
services:
  postgres:
    command: postgres -c ssl=on -c ssl_cert_file=/ssl/postgres.cert -c ssl_key_file=/ssl/postgres.key -c config_file=/var/lib/postgresql/data/postgresql.conf
    environment:
      - POSTGRES_PASSWORD=${POSTGRES__MAIN__PASSWORD:?POSTGRES__MAIN__PASSWORD}
      - POSTGRES_USER=${POSTGRES__MAIN__USER:?POSTGRES__MAIN__USER}
    image: postgres:local
    networks:
      - postgres_public_network
    ports:
      - 5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - postgres-config:/var/lib/postgresql/data/postgresql.conf

networks:
  postgres_public_network:
    external: true

volumes:
  postgres-data:
  postgres-config:
