version: "3.3"

services:

  postgres:
    image: "bitnami/postgresql:13"
    container_name: "postgres"
    labels:
      - "traefik.enable=true"
      - "traefik.tcp.routers.postgres.entrypoints=postgres"
      - "traefik.tcp.routers.postgres.rule=HostSNI(`*`)"
      - "traefik.tcp.services.postgres.loadbalancer.server.port=5432"
    restart: "unless-stopped"
    environment:
      POSTGRESQL_PASSWORD: "${POSTGRES_ADMIN_PASSWORD}"
      POSTGRESQL_USERNAME: "${POSTGRES_ADMIN_USER}"
      POSTGRESQL_DATABASE: "${POSTGRES_ADMIN_DB}"
      POSTGRESQL_ENABLE_TLS: "yes"
      POSTGRESQL_TLS_CERT_FILE: "/certs/postgres.crt"
      POSTGRESQL_TLS_KEY_FILE: "/certs/postgres.key"
    volumes:
      - "postgres-certs:/certs"
    networks:
      - "traefik-public"

volumes:
  postgres-certs:
    external: true
networks:
  traefik-public:
    external: true
      
