version: '3.6'
services:
    postgres:
        image: postgres:11
        restart: unless-stopped
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow
        ports:
            - 5432:5432

    redis:
        image: redis:5
        restart: unless-stopped
        ports:
            - 6379:6379

    webserver:
        build: ../../src/airflow
        image: airflow:1.10.3
        restart: unless-stopped
        depends_on:
            - postgres
            - redis
        environment:
            - AIRFLOW__CORE__EXECUTOR=CeleryExecutor
            - AIRFLOW__CORE__LOAD_EXAMPLES=True
            - AIRFLOW__WEBSERVER__AUTHENTICATE=True
            - AIRFLOW__WEBSERVER__AUTH_BACKEND=airflow.contrib.auth.backends.password_auth
            - AIRFLOW_USER=airflow-user
            - AIRFLOW_PASSWORD=airflow-password
        ports:
            - 8080:8080
        entrypoint: ./entrypoint.sh airflow webserver
        healthcheck:
            test: curl -sf 0.0.0.0:8080/health | grep healthy
            interval: 60s
            timeout: 60s
            retries: 3

    worker:
        image: airflow:1.10.3
        restart: unless-stopped
        depends_on:
            - postgres
            - redis
            - webserver
        environment:
            - AIRFLOW__CORE__EXECUTOR=CeleryExecutor
            - AIRFLOW__CORE__LOAD_EXAMPLES=True
        entrypoint: ./entrypoint.sh airflow worker

    scheduler:
        image: airflow:1.10.3
        restart: unless-stopped
        depends_on:
            - postgres
            - redis
            - webserver
        environment:
            - AIRFLOW__CORE__EXECUTOR=CeleryExecutor
            - AIRFLOW__CORE__LOAD_EXAMPLES=True
        entrypoint: ./entrypoint.sh airflow scheduler

    flower:
        image: airflow:1.10.3
        restart: unless-stopped
        depends_on:
            - postgres
            - redis
            - webserver
        environment:
            - AIRFLOW__CORE__EXECUTOR=CeleryExecutor
        ports:
            - 5555:5555
        entrypoint: ./entrypoint.sh airflow flower --basic_auth=flower-user:flower-password

