version: '3.6'
services:
    postgres:
        image: postgres:11
        restart: unless-stopped
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow
        ports:
            - 5432:5432

    webserver:
        build: ../../src/airflow
        image: airflow:1.10.3
        restart: unless-stopped
        depends_on:
            - postgres
        environment:
            - AIRFLOW__CORE__EXECUTOR=LocalExecutor
            - AIRFLOW__CORE__LOAD_EXAMPLES=True
        ports:
            - 8080:8080
        healthcheck:
            test: curl -sf 0.0.0.0:8080/health | grep healthy
            interval: 60s
            timeout: 60s
            retries: 3
