version: "3.3"

services:

  redis:
    image: bitnami/redis:6.2
    labels:
      - "traefik.enable=true"
      - "traefik.tcp.routers.redis.entrypoints=redis"
      - "traefik.tcp.routers.redis.rule=HostSNI(`*`)"
      - "traefik.tcp.services.redis.loadbalancer.server.port=6379"
    environment:
      - "REDIS_PASSWORD=${REDIS_ADMIN_PASSWORD}"
    networks:
      - "traefik-public"

networks:
  traefik-public:
    external: true
      
